version: "3.8"
services:
  database:
    image: mongo:latest
    restart: always
    volumes:
      - database:/data/db
  backend:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DB_URL: mongodb://database:27017
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
volumes:
  database: {}